name: Generate GitHub Metrics

on:
  schedule:
    - cron: "15 12 * * *"   # ~09:15 BRT
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Generate metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: VieiraGabrielAlexandre
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: America/Sao_Paulo
          filename: github-metrics.svg   # gera na raiz do repo

      - name: Commit metrics file
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update metrics"
          file_pattern: github-metrics.svg
